# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20180628_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addboard',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
