# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20180628_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addboard',
            name='date',
            field=models.CharField(default='2018-06-28', max_length=20),
        ),
    ]
